version: '3'
services:
  rails:
    container_name: rails-graphql-tickets
    build: ./rails-graphql-tickets
    volumes:
      - ./rails-graphql-tickets:/rails:cached
    ports:
      - "3001:3001"
    environment:
      - RAILS_ENV=development
    depends_on:
      - postgres

  react:
    container_name: react-graphql-tickets
    build: ./react-graphql-tickets
    volumes:
      - ./react-graphql-tickets:/react
      - /react/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  postgres:
    image: postgres
    restart: always
    volumes:
      - ./rails-graphql-tickets/tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres